version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:alpine

  worker:
    build: .
    command: celery -A worker.worker worker --loglevel=info
    depends_on:
      - redis
      - web
